development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: microdef_dev
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: microdef_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: microdef
  pool: 5
  username: root
  password: 
